name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Install xmllint
      run: sudo apt-get install libasio-dev nlohmann-json-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make pinpon_test
    - name: make test
      run: build/pinpon_test
