name: Core Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Install dependencies
      run: sudo apt-get install libasio-dev nlohmann-json-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make pinpon_test
    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: pinpon_test
        path: build/pinpon_test
  test:
    name: "Test Core"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Dir
      run: mkdir build
    - name: Download binary
      uses: actions/download-artifact@v1
      with:
        name: pinpon_test
        path: build/
    - name: pinpon_test
      run: cd build && chmod a+x ./pinpon_test && ./pinpon_test
